apiVersion: v1
kind: Pod
metadata:
  name: {{ include "svc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "svc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "svc.chart" . }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    ports:
      - name: http
        containerPort: 80
    # 全局参数作为环境变量
    {{- with .Values.global }}
    env:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    # 服务的配置文件，支持热更新
    volumeMounts:
      - name: config-volume
        mountPath: /app/etc/config
  volumes:
    - name: config-volume
      configMap:
        name: "{{ include "svc.fullname" . }}-cfg"