{{- if .Values.ingress.enabled -}}
{{- $fullName := include "svc.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "svc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "svc.chart" . }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
    # 是否强制使用https
    ingress.kubernetes.io/ssl-redirect: "true"
    # 截取path后作为请求路径传递到后端服务
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ $fullName }}
              # service.yaml内的端口名，集群内部服务之间访问的端口号
              servicePort: https
{{- end }}
