apiVersion: v1
kind: Pod
metadata:
  name: {{ include "svc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "svc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "svc.chart" . }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    ports:
      - name: https
        containerPort: 443
    # 挂载数据卷
    volumeMounts:
      # 服务的配置文件，支持热更新
      - name: config-volume
        mountPath: /app/etc/config
      # 日志存储到宿主机
      - name: log-volume
        mountPath: /app/etc/log
  volumes:
    - name: config-volume
      configMap:
        name: "{{ include "svc.fullname" . }}-cfg"
    # 在宿主机上指定一个目录，挂载到Pod的容器中，存储日志文件
    - name: log-volume
      hostPath:
        path: /home/dt/log
        type: DirectoryOrCreate