<Project Sdk="Dt.Sdk">
    <PropertyGroup>
        <!-- wasm排除数据库初始化功能 -->
        <DefaultItemExcludes Condition="$(IsBrowserWasm) == 'true'">$(DefaultItemExcludes);SysTools\DbInit\**\*</DefaultItemExcludes>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Dt.Core\Dt.Core.csproj" />
        <EmbeddedResource Include="Controls\Policy\Privacy.txt" />
        <EmbeddedResource Include="Controls\Policy\Agreement.txt" />
    </ItemGroup>

    <ItemGroup Condition="$(IsBrowserWasm) != 'true'">
        <EmbeddedResource Include="..\..\Service\src\Dt.Core\Internal\InitMode\InitSql\mysql-init.sql" Link="SysTools\DbInit\Sql\mysql-init.sql" />
        <EmbeddedResource Include="..\..\Service\src\Dt.Core\Internal\InitMode\InitSql\oracle-init.sql" Link="SysTools\DbInit\Sql\oracle-init.sql" />
        <EmbeddedResource Include="..\..\Service\src\Dt.Core\Internal\InitMode\InitSql\postgresql-init.sql" Link="SysTools\DbInit\Sql\postgresql-init.sql" />
        <EmbeddedResource Include="..\..\Service\src\Dt.Core\Internal\InitMode\InitSql\sqlserver-init.sql" Link="SysTools\DbInit\Sql\sqlserver-init.sql" />
    </ItemGroup>
</Project>
